import { type DefaultTheme } from "vitepress";

const leetCode: DefaultTheme.SidebarItem[] = [
  {
    text: "数组",
    base: "/leetcode/",
    collapsed: false,
    items: [
      { text: "1. 两数之和", link: "two-sum" },
      { text: "283. 移动零", link: "move-zeroes" },
      { text: "704. 二分查找", link: "binary-search" },
      { text: "88. 合并两个有序数组", link: "merge-sorted-array" },
      { text: "560. 和为 K 的子数组", link: "subarray-sum-equals-k" },
      { text: "128. 最长连续序列", link: "longest-consecutive-sequence" },
      { text: "209. 长度最小的子数组", link: "minimum-size-subarray-sum" },
      { text: "15. 三数之和", link: "3sum" },
      { text: "33. 搜索旋转排序数组", link: "search-in-rotated-sorted-array" },
      {
        text: "34. 在排序数组中查找元素",
        link: "find-first-and-last-position-of-element-in-sorted-array",
      },
      { text: "179. 最大数", link: "largest-number" },
      { text: "162. 寻找峰值", link: "find-peak-element" },
      { text: "31. 下一个排列", link: "next-permutation" },
      { text: "56. 合并区间", link: "merge-intervals" },
      { text: "215. 数组中的第K个最大元素", link: "kth-largest-element-in-an-array" },
      { text: "912. 排序数组", link: "sort-an-array" },
      { text: "4. 寻找两个正序数组的中位数", link: "median-of-two-sorted-arrays" },
    ],
  },
  {
    text: "字符串",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "415. 字符串相加", link: "add-strings" },
      { text: "14. 最长公共前缀", link: "longest-common-prefix" },
      { text: "43. 字符串相乘", link: "multiply-strings" },
      { text: "8. 字符串转换整数 (atoi)", link: "string-to-integer-atoi" },
      { text: "151. 翻转字符串里的单词", link: "reverse-words-in-a-string" },
      { text: "394. 字符串解码", link: "decode-string" },
      { text: "165. 比较版本号", link: "compare-version-numbers" },
      { text: "3. 无重复字符的最长子串", link: "longest-substring-without-repeating-characters" },
      { text: "76. 最小覆盖子串", link: "minimum-window-substring" },
    ],
  },
  {
    text: "链表",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "206. 反转链表", link: "reverse-linked-list" },
      { text: "141. 环形链表", link: "linked-list-cycle" },
      { text: "142. 环形链表 II", link: "linked-list-cycle-ii" },
      { text: "160. 相交链表", link: "intersection-of-two-linked-lists" },
      { text: "21. 合并两个有序链表", link: "merge-two-sorted-lists" },
      { text: "83. 删除排序链表中的重复元素", link: "remove-duplicates-from-sorted-list" },
      { text: "234. 回文链表", link: "palindrome-linked-list" },
      {
        text: "面试题 22. 链表中倒数第K个节点",
        link: "lian-biao-zhong-dao-shu-di-kge-jie-dian-lcof",
      },
      { text: "92. 反转链表 II", link: "reverse-linked-list-ii" },
      { text: "82. 删除排序链表中的重复元素 II", link: "remove-duplicates-from-sorted-list-ii" },
      { text: "148. 排序链表", link: "sort-list" },
      { text: "2. 两数相加", link: "add-two-numbers" },
      { text: "19. 删除链表的倒数第 N 个结点", link: "remove-nth-node-from-end-of-list" },
      { text: "24. 两两交换链表中的节点", link: "swap-nodes-in-pairs" },
      { text: "143. 重排链表", link: "reorder-list" },
      { text: "23. 合并 K 个升序链表", link: "merge-k-sorted-lists" },
      { text: "25. K 个一组翻转链表", link: "reverse-nodes-in-k-group" },
    ],
  },
  {
    text: "栈与队列",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "20. 有效的括号", link: "valid-parentheses" },
      { text: "232. 用栈实现队列", link: "implement-queue-using-stacks" },
      { text: "155. 最小栈", link: "min-stack" },
      { text: "32. 最长有效括号", link: "longest-valid-parentheses" },
      { text: "239. 滑动窗口最大值", link: "sliding-window-maximum" },
      { text: "227. 基本计算器 II", link: "basic-calculator-ii" },
      { text: "224. 基本计算器", link: "basic-calculator" },
    ],
  },
  {
    text: "二叉树",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "94. 二叉树的中序遍历", link: "binary-tree-inorder-traversal" },
      { text: "101. 对称二叉树", link: "symmetric-tree" },
      { text: "110. 平衡二叉树", link: "balanced-binary-tree" },
      { text: "543. 二叉树的直径", link: "diameter-of-binary-tree" },
      { text: "104. 二叉树的最大深度", link: "maximum-depth-of-binary-tree" },
      { text: "226. 翻转二叉树", link: "invert-binary-tree" },
      { text: "112. 路径总和", link: "path-sum" },
      { text: "98. 验证二叉搜索树", link: "validate-binary-search-tree" },
      { text: "102. 二叉树的层序遍历", link: "binary-tree-level-order-traversal" },
      { text: "103. 二叉树的锯齿形层次遍历", link: "binary-tree-zigzag-level-order-traversal" },
      { text: "236. 二叉树的最近公共祖先", link: "lowest-common-ancestor-of-a-binary-tree" },
      { text: "199. 二叉树的右视图", link: "binary-tree-right-side-view" },
      { text: "129. 求根到叶子节点数字之和", link: "sum-root-to-leaf-numbers" },
      { text: "662. 二叉树最大宽度", link: "maximum-width-of-binary-tree" },
      { text: "113. 路径总和 II", link: "path-sum-ii" },
      {
        text: "105. 从前序与中序遍历序列构造二叉树",
        link: "construct-binary-tree-from-preorder-and-inorder-traversal",
      },
      { text: "124. 二叉树中的最大路径和", link: "binary-tree-maximum-path-sum" },
    ],
  },
  {
    text: "回溯法",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "78. 子集", link: "subsets" },
      { text: "46. 全排列", link: "permutations" },
      { text: "39. 组合总和", link: "combination-sum" },
      { text: "22. 括号生成", link: "generate-parentheses" },
      { text: "93. 复原IP地址", link: "restore-ip-addresses" },
    ],
  },
  {
    text: "动态规划",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "70. 爬楼梯", link: "climbing-stairs" },
      { text: "121. 买卖股票的最佳时机", link: "best-time-to-buy-and-sell-stock" },
      { text: "62. 不同路径", link: "unique-paths" },
      { text: "64. 最小路径和", link: "minimum-path-sum" },
      { text: "221. 最大正方形", link: "maximal-square" },
      { text: "53. 最大子数组和", link: "maximum-subarray" },
      { text: "152. 乘积最大子数组", link: "maximum-product-subarray" },
      { text: "718. 最长重复子数组", link: "maximum-length-of-repeated-subarray" },
      { text: "42. 接雨水", link: "trapping-rain-water" },
      { text: "139. 单词拆分", link: "word-break" },
      { text: "5. 最长回文子串", link: "longest-palindromic-substring" },
      { text: "122. 买卖股票的最佳时机 II", link: "best-time-to-buy-and-sell-stock-ii" },
      { text: "322. 零钱兑换", link: "coin-change" },
      { text: "300. 最长上升子序列", link: "longest-increasing-subsequence" },
      { text: "1143. 最长公共子序列", link: "longest-common-subsequence" },
      { text: "72. 编辑距离", link: "edit-distance" },
    ],
  },
  {
    text: "图论",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "240. 搜索二维矩阵 II", link: "search-a-2d-matrix-ii" },
      { text: "54. 螺旋矩阵", link: "spiral-matrix" },
      { text: "48. 旋转图像", link: "rotate-image" },
      { text: "200. 岛屿数量", link: "number-of-islands" },
      { text: "695. 岛屿的最大面积", link: "max-area-of-island" },
    ],
  },
  {
    text: "数学",
    base: "/leetcode/",
    collapsed: true,
    items: [
      { text: "69. x 的平方根", link: "sqrtx" },
      { text: "169. 多数元素", link: "majority-element" },
      { text: "470. 用 Rand7() 实现 Rand10()", link: "implement-rand10-using-rand7" },
      { text: "41. 缺失的第一个正数", link: "first-missing-positive" },
    ],
  },
];

export default leetCode;
