/**
 * AUTO-GENERATED by scripts/gen-runner-data.mjs — 请勿手动编辑。
 * 重新生成：npm run gen:runner（npm run build 时也会自动执行）。
 *
 * 数据来源：docs/leetcode/*.md 的 frontmatter（entry + testcases）与 code-group 代码块。
 */

export interface GeneratedProblem {
  python?: string
  java?: string
}

export const problemsData: Record<string, GeneratedProblem> = {
  "climbing-stairs": { python: "class Solution:\r\n    def climbStairs(self, n: int) -> int:\r\n        a, b = 0, 1\r\n        for _ in range(n):\r\n            a, b = b, a + b\r\n        return b", java: "class Solution {\r\n    public int climbStairs(int n) {\r\n        int a = 0, b = 1;\r\n        for (int i = 0; i < n; ++i) {\r\n            int c = a + b;\r\n            a = b;\r\n            b = c;\r\n        }\r\n        return b;\r\n    }\r\n}" },
  "two-sum": { python: "class Solution:\r\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\r\n        d = {}\r\n        for i, x in enumerate(nums):\r\n            y = target - x\r\n            if y in d:\r\n                return [d[y], i]\r\n            d[x] = i", java: "class Solution {\r\n    public int[] twoSum(int[] nums, int target) {\r\n        Map<Integer, Integer> d = new HashMap<>();\r\n        for (int i = 0;; ++i) {\r\n            int x = nums[i];\r\n            int y = target - x;\r\n            if (d.containsKey(y)) {\r\n                return new int[] {d.get(y), i};\r\n            }\r\n            d.put(x, i);\r\n        }\r\n    }\r\n}" },
  "valid-parentheses": { python: "class Solution:\r\n    def isValid(self, s: str) -> bool:\r\n        stk = []\r\n        d = {'()', '[]', '{}'}\r\n        for c in s:\r\n            if c in '({[':\r\n                stk.append(c)\r\n            elif not stk or stk.pop() + c not in d:\r\n                return False\r\n        return not stk", java: "class Solution {\r\n    public boolean isValid(String s) {\r\n        Deque<Character> stk = new ArrayDeque<>();\r\n        for (char c : s.toCharArray()) {\r\n            if (c == '(' || c == '{' || c == '[') {\r\n                stk.push(c);\r\n            } else if (stk.isEmpty() || !match(stk.pop(), c)) {\r\n                return false;\r\n            }\r\n        }\r\n        return stk.isEmpty();\r\n    }\r\n\r\n    private boolean match(char l, char r) {\r\n        return (l == '(' && r == ')') || (l == '{' && r == '}') || (l == '[' && r == ']');\r\n    }\r\n}" },
}
